export const GET_USER_BY_FACEBOOK = "GET_USER_BY_FACEBOOK";
export const GET_USER_BY_FACEBOOK_SUCCESS = "GET_USER_BY_FACEBOOK_SUCCESS";
export const GET_USER_BY_FACEBOOK_FAIL = "GET_USER_BY_FACEBOOK_FAIL";

export const CLEAR_USER = "CLEAR_USER";
export const CLEAR_CONTACTS = "CLEAR_CONTACTS";
export const CLEAR_MAIN_INFO = "CLEAR_MAIN_INFO";
export const CHANGE_SHOW_HEADER_FLAG = "CHANGE_SHOW_HEADER_FLAG";

export const GET_CONTACTS = "GET_CONTACTS";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";
export const GET_CONTACTS_FAIL = "GET_CONTACTS_FAIL";

export const GET_MAIN_INFO = "GET_MAIN_INFO";
export const GET_MAIN_INFO_SUCCESS = "GET_MAIN_INFO_SUCCESS";
export const GET_MAIN_INFO_FAIL = "GET_MAIN_INFO_FAIL";